version: "3.9"
services:
  cassandra:
    image: 'cassandra:4.1.2'
    container_name: studprokat_cassandra
    environment:
      - 'CASSANDRA_DC=dc1'
      - 'CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch'
      - 'CASSANDRA_CLUSTER_NAME=cluster1'
    ports:
      - '9042:9042'
    volumes:
      - '~/data/cassandra:/var/lib/cassandra'
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5

  studprokat-backend:
    image: {{ env.IMAGE_ID }}
    container_name: studprokat_backend
    depends_on:
      cassandra:
        condition: service_healthy
    ports:
      - '8080:8080'
      - '9090:9090'

  # automatically pull updated container from ghcr
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: studprokat_backend