spring:
  cassandra:
    keyspace-name: studprokat
    schema-action: create_if_not_exists
    local-datacenter: dc1
    contact-points: 127.0.0.1:9042
    username: cassandra
    password: cassandra
